deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: $REGION
  app: $APP_NAME
  env: $ENV_NAME
  bucket_name: $BUCKET_NAME

sudo: required
dist: trusty
language: node_js
node_js:
  - '6'
branches:
  only:
    - master
cache:
-  yarn: true
   directories:
      - ./node_modules


before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn config set spin false
  - yarn config set progress false

  - export PATH="$HOME/.yarn/bin:$PATH"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- yarn global add @angular/cli
- yarn global add karma
- yarn install
- ng build
install:
- yarn --frozen-lockfile
script: 
  ng test
  ng serve